apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1-service
    spec:
      containers:
      - name: service1
        imagePullPolicy: Never
        image: microservice1
        ports:
        - containerPort: 5001
