name: Deploy to Minikube
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to minikube in Github Actions!
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        id: minikube
        with:
          driver: docker
          wait: all
      - name: Try the cluster
        run: kubectl get pods -A
      - name: Setup Docker environment
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
      - name: Print current app version
        run: |
          echo "current_version=$(grep '# version' version.md | cut -d ' ' -f3)" >> $GITHUB_ENV
          echo "Current version: ${{ env.current_version }}"
      - name: Generate Modified Deployment yml
        run: |
          sed -e "s/microservice1/microservice1:${{ env.current_version }}/g" deployment-service1.yml > modified-deployment-service1.yml
          sed -e "s/microservice2/microservice2:${{ env.current_version }}/g" deployment-service2.yml > modified-deployment-service2.yml
      - name: Build microservice1 image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -f ./service1/Dockerfile -t microservice1:${{ env.current_version }} ./service1
      - name: Build microservice2 image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -f ./service2/Dockerfile -t microservice2:${{ env.current_version }} ./service2
      - name: Print docker images
        run: |
          eval $(minikube -p minikube docker-env)
          docker images
      - name: Deploy to minikube
        run: |
          eval $(minikube -p minikube docker-env)
          kubectl apply -f modified-deployment-service1.yml
          kubectl apply -f modified-deployment-service2.yml
          kubectl apply -f service-service1.yml
          kubectl apply -f service-service2.yml
      - name: List deployments
        run: kubectl get deploy
      - name: List services
        run: kubectl get service
      - name: List pods
        run: kubectl get pods
      - name: Wait for pods to be ready
        run: |
          chmod +x ./check_pods.sh
          ./check_pods.sh
        timeout-minutes: 15
      - name: Test service URLs
        run: |
          eval $(minikube -p minikube docker-env)
          sleep 30
          minikube service list
          echo "------------------service details------------------"
          kubectl get service service2-service
          echo "------------------opening the service------------------"
          echo 
          curl $(minikube service service2-service --url)/
